### PR TITLE
Make the deeplink url configurable in the config options

### PR DESCRIPTION
**Pull request by sebphil**
This PR aims at allowing a new `url` config option which can be used instead of the query param. The query param is still supported, and when provided it takes precedence over the config option.

### CODE REVIEW

**Comment by mderazon** [comment]
Thanks @sebphil .
I am curious to know what functionality was missing for you. I assume you could make sure to always pass a url in the query param no ?

**Comment by sebphil** [comment]
Hi @mderazon , thanks for the quick reply.
I'm currently in the process of rewriting an old webapp, and that webapp hosted a deeplink routing feature that I need to port to the new webapp. In the old webapp, the deeplink url was not defined in the query params but was instead configured directly in the webapp. Now, in my new webapp, I need to be backwards compatible with the entry point the old webapp provided, because I cannot easily change the client code of that entry point. Hence the need to be able to provide the deeplink url in the config and not in the query params.

**Comment by mderazon** [comment]
Got it. Thanks for taking the time to write PR with tests

**Comment by sebphil** [comment]
Thank you very much!

**Pull request merged**
